### ISSUE TITLE
Two-sample test: population distribution "reveal"

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#101]
What do you guys all think about what we should "reveal" for the two-sample case? I think the best option is: Show the distributions of population 1 and 2, overlaid on the same graph, where dots of each population have different colors. I also think we could show the location of mean 1 and the location of mean 2 as vertical lines. 

Below is what we currently show (which does not make sense for this case)
<img width="630" alt="Screen Shot 2021-07-05 at 8 46 31 PM" src="https://user-images.githubusercontent.com/53241468/124526948-352dd980-ddd2-11eb-8152-b0c90bdf93aa.png">

**Comment by ethansaxenian** [comment]
I agree this doesn't make sense; on the branch for the two-sample simulation, I have changed this to show the two populations and their respective means. Definitely a good idea to make this a separate issue, however.

**Comment by ProfessorAmanda** [comment]
Ah, good! Should I close this issue or leave it open?

**Comment by ethansaxenian** [comment]
I think we should leave it open until the PR that implements this is merged.
