### ISSUE TITLE
Two-sample hypothesis test: sample data that we show

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#102]
Another very small comment on the two-sample case. In the "results" box (shown below), can we also show: Mean of Sample 1, Mean of Sample 2, Standard Deviation of Population/Sample 1, Standard Deviation of Population/Sample 2, Test Statistic, and p-value? (Show the pop std deviations if they are assumed to be known, show sample standard deviations if pop standard deviations are not assumed to be known. I think! We could disagree about what to show, potentially).

<img width="638" alt="Screen Shot 2021-07-05 at 8 51 00 PM" src="https://user-images.githubusercontent.com/53241468/124527111-b5ecd580-ddd2-11eb-8c15-7229f8d1f2ac.png">

**Comment by ethansaxenian** [comment]
That all makes sense.

What does `P(Z > teststat)` mean? (this was here from before)

**Comment by ProfessorAmanda** [comment]
That's the literal definition of the p-value. We actually have to fix that, too, now that you mention it. That statement needs to change depending on the alternative hypothesis. There are three cases:

1. Ha: H_a: μ_1 - μ_2 < 0 -- > the p-value is P ( Z < test stat)
2. Ha: H_a: μ_1 - μ_2 > 0 -- > the p-value is P ( Z > test stat)
3. Ha: H_a: μ_1 - μ_2 != 0 -- > the p-value is P ( Z > |test stat|)

We will need to fix this for the one-sample tests as well. Let me know if you'd like me to make that a separate issue.

**Comment by ethansaxenian** [comment]
I think that's similar enough to talk about here!

**Comment by ethansaxenian** [comment]
For a one-sample test, is it:

1. H_a: μ < 64 --> P(Z < test stat)
2. H_a: μ > 64 --> P(Z > test stat)
3. H_a: μ ≠ 64 --> P(Z > |test stat|)

?

**Comment by ProfessorAmanda** [comment]
Yes, exactly right.
