### ISSUE TITLE
Add "Convert to standard normal" option

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#110]
See Hypothesis testing module for example - use checkbox

**Comment by ethansaxenian** [comment]
@tbyker what is the formula for this? In CLT we used `(sampleMean - popMean) / (popSD / sqrt(sampleSize))`, but for this module we are plotting slopes, not means.

**Comment by tbyker** [comment]
hmmm.  I am suddenly wondering if it might be conceptually similar, but mathematically a little more complicated.  Did I give you the Stock and Watson text book?  If so, this could be a good time to read sections 4.5 Sampling Distribution of the OLS Estimators (including some of the appendix math) and then Chapter 5 on Hypothesis Testing and Confidence Intervals in Regression.  I am working on some other stuff right now, but if you read through that maybe we can chat after and I will have time to look too.  There is an equation in key concept 4.4 for the variance of beta_1_hat (and beta_0_hat) that I think we will need to use to standardize.  If you don't have the book, I have an extra copy.
