### ISSUE TITLE
Should the "first population" have a mean of 64?

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#111]
Should the mean of the first population for a two-sample Hypothesis test be 64 (the same as the original population) or should this be randomized? Currently it is randomized but I am not sure if this was the intention.

**Comment by ProfessorAmanda** [comment]
Ah, good question. I think the mean of population 1 should be fixed at 64, while the mean of population 2 should be randomized.

**Comment by ethansaxenian** [comment]
But in a one-sample test, we _do_ want the population mean to be randomized, correct?

**Comment by ProfessorAmanda** [comment]
Yes, in the one-sample test, the mean should be randomized.

**Comment by ethansaxenian** [comment]
And what about the standard deviations?

**Comment by ProfessorAmanda** [comment]
How are they working right now? I think it would be cool to also randomize the standard deviations for the population in the one-sample case, and the standard deviation for population 2 in the two-sample case.

**Comment by ethansaxenian** [comment]
Currently they are all randomized in both cases.

So to clarify, we want a fixed mean but random standard deviation for the "original" population in the two-sample case?

**Comment by ethansaxenian** [comment]
One more thing: currently for the simulation part of the module we are generating two populations both with a mean of mu0. We want to keep this as is because these two populations are different that the previous two (?)

**Comment by ethansaxenian** [comment]
And conceptually, for a one-sample test the population we are sampling from is the "new" population, i.e. the cows _after_ their feed was changed. For a two-sample test the "first population" is the original population (pre-feed-change) and the "second population" is the "new" population. Do I have this correct?

**Comment by ProfessorAmanda** [comment]
Sorry for the delay, got distracted at home (buying hearing aids for my mother, lol). 

1. In the one-sample test, let's randomize the population mean and standard deviation.
2. In the two-sample case, let's fix the mean and std. dev of population 1 and randomize the mean and std. dev. for population 2.
3. For the two-sample simulation, the population means should be the case. The standard deviations should be what they end up being in the main part above (first pop std dev fixed, second pop had been randomized above).
4. Yes, you have the concept correct! 

Hope these help. I'm available for further clarification, too (just might take me a bit to get back to you).
