### ISSUE TITLE
Migrate from Reactstrap to React-Bootstrap

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#114]
The website currently uses Reactstrap for much of its front-end styling. We might consider switching to React-Bootstrap, a similar library that is older, more popular, and has much better documentation, including examples using hooks (where Reactstrap has examples using classes).

**Comment by ProfessorAmanda** [comment]
How heavy a lift would it be to make the conversion, would you guess?

**Comment by ethansaxenian** [comment]
Well react-boostrap and reactstrap are compatible, so it could be more of a gradual process. Although I suspect a global find + replace might be of some help here :)
