### ISSUE TITLE
Check math for p-values

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#117]
Hi folks! Things are looking really good. I have a couple comments to make sure we are doing the math correctly for hypothesis tests.

I'm looking at the case for a two-sample test where the alternative hypothesis asserts that the mean of population 2 should be higher than the mean of population 1.  In this example, the mean of population 1 actually turned out to be higher, so we should fail to reject, and the p-value should be very large (certainly larger than .5). But the result has us reject Ho with a small p-value. I suspect that the p-value is just being calculated incorrectly. Check the reveal as well. 

<img width="192" alt="Screen Shot 2021-07-08 at 11 27 21 AM" src="https://user-images.githubusercontent.com/53241468/124949486-9b3b7c00-dfdf-11eb-82f5-36ebe8fe56fc.png">

<img width="492" alt="Screen Shot 2021-07-08 at 11 26 50 AM" src="https://user-images.githubusercontent.com/53241468/124949521-a2628a00-dfdf-11eb-830b-3ebb279af2b6.png">

<img width="622" alt="Screen Shot 2021-07-08 at 11 27 14 AM" src="https://user-images.githubusercontent.com/53241468/124949545-a8586b00-dfdf-11eb-9d48-c5f1d748268b.png">

This also seems to be an issue with one-sample tests. See the example below. The p-value for this case should be more like .75 (definitely larger than .5).  

<img width="472" alt="Screen Shot 2021-07-08 at 11 32 11 AM" src="https://user-images.githubusercontent.com/53241468/124950132-26b50d00-dfe0-11eb-9f4a-0f30d8561e6c.png">

Hope you guys are all doing great this week!

**Comment by ProfessorAmanda** [comment]
BTW this is all off the master branch.

**Comment by DavidGmidd** [comment]
Hi @ProfessorAmanda, just to confirm: 
1. When we know sigma for a two-sample test, we obtain the p-value via z-test using a z-score
2. When we do not know sigma for a two-sample test, we obtain the p-value with a t-test, using a t-score. 
 
Are these statements accurate?  Thank you!

**Comment by ProfessorAmanda** [comment]
Yes, that is all correct, but be careful about which "tail" of probability the function spits out. In the two tailed example above, the function has given the probably that Z was less than -.7, while what we wanted was the probability that Z was greater than .7. It helps to draw a picture.
