### ISSUE TITLE
Generate second dataset for OLS Estimators

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#122]
see page 20 of [jobcorpimpactbenefit.pdf](https://github.com/ProfessorAmanda/econsimulations/files/6793163/jobcorpimpactbenefit.pdf) for the results plot and page 21 for the average earnings of the two groups that we will use.

**Comment by ethansaxenian** [comment]
@tbyker when we sample from this population, do we care about the distribution of this sample among the two categories? Or do we want to be sampling exactly half from one category and the other half from the other category?

Or, if we take a sample of size 10, say, do we want to sample 10 from the first category _and_ 10 from the second?

**Comment by tbyker** [comment]
Meaning should the treatment and control group be of the same size?  Yes, let's start with that.  Sometimes in practice the two groups are different for various reasons (it might list the actual sample sizes in that report).


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
No, I'm talking about sampling from the data once we've plotted the initial population, i.e. the interactive portion of the module.

**Comment by tbyker** [comment]
No, we just want to take a random sample from the dataset as a whole.  Well, I guess we might need to guarantee that they take a big enough sample that they get at least one from each group.  But conceptually, we want to sample randomly just like in the study time and test scores example.  In practice we won't be able to estimate a slope if our sample only winds up containing observations from one of the two groups.  Any thoughts about a clever "random"-ish way to solve this?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
At the very least we can easily restrict the minimum sample size to be 2. If we want to ensure that data points come from both groups, it would be doable, but quite a hassle and very messy. I’ll keep thinking!

**Comment by tbyker** [comment]
How about this: the plotted data set needs to include at least 2 points and the there are actually 2 randomly selected datasets combined: The first is one random point selected from each group and then a second dataset that is just a random draw from the full population -- the user sees this as "one sample" but on the backend it is two.  Not exactly random, but will ensure at least one point from each group?  And maybe also for this module we just say you have to draw a minimum of 6 points or something like that?  Not sure if the second stipulation is necessary.  Maybe start with the first and see how things go.

A completely different idea I just had... and maybe this is better.  We take a random sample... and then if all observations are from one group we have a pop up box that says, "Oh no, you only drew observations from one of the treatment arms (treat or control), so we can't estimate a regression line, try again."

Maybe I like this last idea the best.

Thoughts?




**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
I like the last idea as well, however how to we want to handle this when the user is drawing many samples at once?

**Comment by tbyker** [comment]
In the simulation could we just throw out any sample that doesn't contain at least one obs from each group?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Yes!
