### ISSUE TITLE
Intro paragraphs for Joint Distributions, Least Squares, Omitted Variable Bias

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#123]
These 3 modules don't have an introductory paragraph that is displayed once the user enters the module. Perhaps this isn't needed, but all the other modules currently have one (with the exception of OLS Estimators which is still a work in progress)

**Comment by ProfessorAmanda** [comment]
Plus I need menu text for hypothesis testing.

**Comment by tbyker** [comment]
Intro text for:
**Least Squares**: The Ordinary Least Squares method estimates the intercept and slope of a line that “best fits” the observed data by minimizing the sum of the squared distances between the points and the line.

**Joint Distributions**:  Covariance measures the extent to which two random variables move together, or “co-vary.”  Correlation is an alternative measure of how two variables co-move that is scaled by the standard deviation of the variables and ranges between -1 and 1.  The mean and variance of each individual random variable factor into the calculation of covariance (or correlation), but pairs of random variables with same underlying distributions could have very different correlations.  

**Omitted Variable Bias**: 	Omitted Variable Bias (OVB) is the bias in a regression estimator that arises when there is a variable (V) which is not included in the regression that is correlated with the regressor (X) and is a determinant of the outcome (Y).
In the regression model Y_i=β_0+β_1 X_i+δV_i+ϵ_i where V is omitted from the regression estimation, the OVB is described as the final term in the following expression 

                     β_1 □(→┴p ) β ̂_1+(δCov(X,V))/(Var(X))

^^^ is from our teaching materials and I am including a screen shot below.  Can you get this notation in there?  Amanda, do you think it is too much to put this on the page itself?

![image](https://user-images.githubusercontent.com/66968295/127685606-326cb915-672e-4b6d-95f5-7a86348c33d7.png)

**Comment by ProfessorAmanda** [comment]
I don't think that's too much text for the OVB page.
