### ISSUE TITLE
Clicking "run" should clear all points

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#131]
In the simulations for hypothesis testing and dist'n of betas (others?), clicking "run" should clear all previous points.

**Comment by ethansaxenian** [comment]
Can we call the module "Distribution of Betas" instead of "Sample Distribution of OLS Estimators"?

**Comment by ProfessorAmanda** [comment]
Okay I just spent five minutes trying out variations, and "Sampling Distribution of OLS Estimators" is the best because it's short and accurate. To be totally accurate, the "betas" version would be, "Sampling Distribution of Beta Hats," or "Sampling Distribution of Beta Hats Derived under OLS" (pure poetry, right?). But I defer to my wise collaborator TB on this one.

**Comment by ethansaxenian** [comment]
Ok, that's fine! In that case I had already made a GitHub label for the module :)

In regards to the actual issue, do we want this behavior in Confidence Intervals as well?

**Comment by ProfessorAmanda** [comment]
Ah, good call! 

Yes, I think reasonable to do this for CIs.
