### ISSUE TITLE
Post handout on matrix algebra for OLS

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#132]

**Comment by tbyker** [comment]
Start with Stock and Watson Chapter 18, intro and section 18.1.  That might be enough, but I am also attaching a handout that might wind up being overkill.  I also have my notes from when I taught regression with linear algebra in grad school. I could walk you through those if needed. 
[matrix_OLS_notes.pdf](https://github.com/ProfessorAmanda/econsimulations/files/6818637/matrix_OLS_notes.pdf)

**Comment by tbyker** [comment]
Here are the scans from Stock and Watson.  The last two pages are from the appendix and have a quick review of matrix algebra.
[Stock_and_Watson_Multiple_Reg_Matrix_Algebra.pdf](https://github.com/ProfessorAmanda/econsimulations/files/6851844/Stock_and_Watson_Multiple_Reg_Matrix_Algebra.pdf)
