### ISSUE TITLE
Standardize option not plotting points

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#135]
I just noticed that the actual standardized data points are not being plotted on the beta distribution graphs, rather it's just a normal curve. I assume this is a bug.

@ProfessorAmanda, @tbyker do we want the normal curve to be displayed as well?

**Comment by tbyker** [comment]
can you give me commands to look?



**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
From: Ethan Saxenian ***@***.***>
Sent: Friday, July 16, 2021 12:26 PM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Byker, Tanya S. ***@***.***>; Mention ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Standardize option not plotting points (#135)


I just noticed that the actual standardized data points are not being plotted on the beta distribution graphs, rather it's just a normal curve. I assume this is a bug.

@ProfessorAmanda<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfessorAmanda&data=04%7C01%7Ctbyker%40middlebury.edu%7C44c635cb53ee41fe9fba08d948767ead%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637620496029827284%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kOgFFyKrXOJja1V8qQFHBQUcg3%2BGyy8HXEidYlEymIk%3D&reserved=0>, @tbyker<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftbyker&data=04%7C01%7Ctbyker%40middlebury.edu%7C44c635cb53ee41fe9fba08d948767ead%7Ca1bb0a191576421dbe93b3a7d4b6dcaa%7C1%7C0%7C637620496029837278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9%2BkL%2BU6AEPQBMjcl10gmnK1jRQOuv2EnlGTCeCkL1QE%3D&reserved=0> do we want the normal curve to be displayed as well?

**Comment by ethansaxenian** [comment]
This is on the master branch, so

```
git checkout master
git pull
npm start
```

**Comment by tbyker** [comment]
Hmm.  Yeah.  We definitely want the standardized points plotted.  The question is whether we also want a normal curve plotted over them.  this is something we discussed in the past for the original CLT module.  Amanda, I am guessing it would just be a standard normal plot with mean zero and sd=1.  And this would overlay and you can see how close our simulation "histogram" is to the actual standard normal.  Can we try that, Ethan?

T


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
It will make life much more difficult for me, but yes we can!

**Comment by tbyker** [comment]
LOL.  Well, just doing the dots is a first step.  You can ascribe a level of priority to the curve overlay based on your level of interest in doing it relative to other things on the list.

T


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
I'm confused! Ethan, I thought you already were able to plot the normal curve but that the dots weren't showing up. It's totally fine if the normal curve is just "empirical" to the points.

**Comment by tbyker** [comment]
I think he is saying having both dots and curve is complicated


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ProfessorAmanda** [comment]
Ah, right, I remember this coming up previously.

**Comment by ethansaxenian** [comment]
The reason is because the y-axis is not the same for both plots: the points are a dot plot so the y-axis goes 1, 2, 3, etc... and the normal curve is between 0 and 1. So I need to scale the dot plot points to fit inside the normal curve.

I'm probably exaggerating the difficulty. It's just trial-and-error.

**Comment by ProfessorAmanda** [comment]
Right, right, I remember now. Yeah sounds annoying but possible.
