### ISSUE TITLE
Incorrect calculation of p-value for t-test?

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#138]
Currently we are calculating the p-value for a z-test according to these rules:
![IMG_2578](https://user-images.githubusercontent.com/67524957/126003306-0594d678-f65c-42d2-b2d9-286769fe80d4.jpeg)

However, no such calculations are happening for a t-test.

**Comment by ethansaxenian** [comment]
@ProfessorAmanda @tbyker I assume the logic would be the same for a t-test? Comparing the test stat based on the direction of the operator in the hypothesis?

**Comment by ProfessorAmanda** [comment]
(I also put this in my email to you:) You'll want to make sure that the jstat t function is calculating p-values similarly to the way it does for z. You can check by using similar input values. For large sample sizes, z and t should give you approximately similar numbers. If it does not, we will have to figure out what the t function is spitting out.
