### ISSUE TITLE
Possible new idea: ANOVA (F-test) Simulation 

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#139]
For the sake of stats class, we've done a good job creating simulations that help with the core ideas. One slightly niche idea I've had, and which I haven't seen a lot of good material on, is a simulation of the ANOVA F-test. The F-test allows you to test hypotheses about the equality of more than two population means (up to any integer k), which is nifty.

The idea: allow users to select a number of populations, each population's mean, each population's standard deviation, and the sample size to be drawn from each population. Then plot the resulting samples and show the results for MSTR, MSE, F, and p-value.

For the math: see Chapters 10.4 and 10.5 of the Anderson, Sweeney, Williams textbook. 

I've looked around for some existing simulations. [This one](http://www.rossmanchance.com/applets/AnovaSim.html) gets really close, but it does not show the samples selected from the populations, and it only allows you to examine 3 populations. 

[This one](https://digitalfirst.bfwpub.com/stats_applet/stats_applet_1_anova.html) is awful, lol.

**Comment by ProfessorAmanda** [comment]
Below is a mockup of the ANOVA module. Take some time to get to know the key equations (esp. the overall sample mean, MSTR, and MSE) before you get started. 

[Simulation_ANOVA.docx](https://github.com/ProfessorAmanda/econsimulations/files/6933778/Simulation_ANOVA.docx)

**Comment by ethansaxenian** [comment]
![IMG_2636](https://user-images.githubusercontent.com/67524957/128710841-7c6722fd-efff-4c21-af07-d093e1d78621.jpeg)

**Comment by ethansaxenian** [comment]
Suggestions based on most recent pull:

1. Options for the number of populations should start at 1.
2. Can we make all the graphs smaller? I'd go so far as to make them 25% smaller.
3.  Can we give all graphs the same x axis so that the user can see the relative locations? This make require us to constrain the possible population means.
4. I'd like to present the results in a table (roughly like what I had in the Word doc mockup). That's just how folks are used to seeing ANOVA results presented.
5. It might be useful to present the sample means and standard deviations? (Maybe as a vertical line indicating the location of the sample mean, with text showing the sample mean and sample standard deviation)
6. Population and sample numbering should begin with 1.
7. Set sample sizes next to population means, so that when they click the "Generate Populations and Samples" button it does both for them.

**Comment by ethansaxenian** [comment]
Everything from the above comment has now been implemented! What else needs to be done?

**Comment by ProfessorAmanda** [comment]
Looks much better! A few small suggestions now that I've gotten to play with it. Then, I think, we put it down for a while!

- [ ] Decrease horizontal space between where you set the means of the populations and where you set the sample sizes.
- [ ] Separate the "Generate Populations and Samples" button into two buttons, side by side. "Generate Populations" will create all the graphs (population graphs, with dots, and sample graphs, blank for now), and a second button right next to it, "Take Samples" will take the samples put the dots on the sample graphs. I think we need to drive home that samples are being take. What do you think? 
- [ ] In the results table, move the F stat and the p-value over one cell to the left.

**Comment by ethansaxenian** [comment]
I can't figure out how to decrease horizontal space without messing up the layout on smaller screen sizes. Any other layout ideas?

**Comment by ProfessorAmanda** [comment]
Ah I gotcha. How about moving the input boxes for setting the number of populations and standard deviations to right next to their text? (I see a big space, like below). It might help?

![Screen Shot 2021-08-10 at 5 03 42 PM](https://user-images.githubusercontent.com/53241468/128934732-ca7dcfff-fc26-468e-a87a-1893c924f5e7.png)

**Comment by ProfessorAmanda** [comment]
Also, maybe move "set the standard deviations" to right below setting the number of populations.

**Comment by ProfessorAmanda** [comment]
One more thing that will help (and will make it make sense): the minimum number of populations should actually be 2.

**Comment by ethansaxenian** [comment]
Ok it now looks a bid weird while adjusting the screen size, but at any one size I think it should be ok.

**Comment by ProfessorAmanda** [comment]
Yeah I think it look much more acceptable on average now. In fact, I think it's lookin pretty good! This is probably a good stopping point. Leave it me to write up the menu and introductory text while you're away. Have fun!

**Comment by ProfessorAmanda** [comment]
In fact, go ahead and merge to master?
