### ISSUE TITLE
3D regression updates

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#144]
The `3d-regression` branch now has buttons to toggle the best fit line/plane. I've also labeled the axes and styled the markers a bit to make them more distinct.

A few things we still need:
- A better name for the module?
- A graph title
- Better labels for the buttons

**Comment by tbyker** [comment]
some questions and comments on the 3-d plot:
1) for the little buttons at the top, is there anyway to label what they are without having to hover over them?  I am trying to think how a user who isn't being guided can figure out what they are supposed to do.  
2) Is there a way to set the default view of the 3-d graph.  there is kind a of a "looking down" on it view in the current default.  Maybe this isn't something you can change.  But my ideal would be more like a flat view with str and el_pct sitting flat if that makes any sense.
3) Can we expand the scale on the axes a little?  For example, STR ranging from 10 to 30.  And el_pct 0 to 100.  test scores 600 to 720.  let's see what that looks like for a start
4) For the displays, I know the graphing tool wants to call Test Scores "Z", but I would like to refer to Test Scores as the "outcome" and we call that "Y," and then STR is X_1 and el_pct is X_2.  We could even make the text specific to the example like "plot Test Scores vs Student Teacher Ratio" if that isn't too much text.
5) For starters, we can call this module: "Multiple Regression"

**Comment by ethansaxenian** [comment]
Unfortunately, I don't think (1) is possible. However, 2-5 have now been implemented!

**Comment by tbyker** [comment]
For the default, I was thinking this:
![image](https://user-images.githubusercontent.com/66968295/127703792-46995961-dea2-4d6b-8f46-853620c3c244.png

**Comment by ethansaxenian** [comment]
> For the default, I was thinking this:
> ![image](https://user-images.githubusercontent.com/66968295/127703792-46995961-dea2-4d6b-8f46-853620c3c244.png)

Ah, gotcha

**Comment by ethansaxenian** [comment]
Fixed!

**Comment by tbyker** [comment]
Couple little things:
1) can we match the axis scales in the 2-d plots to what we did for the 3-d plot
2) when describing the 2-d plots ... this is nit picky ... list the variable that appears on the "y" axis first.  So "Plot Test Scores vs. Percent English Learners"  etc

**Comment by ethansaxenian** [comment]
Fixed

**Comment by tbyker** [comment]
Let's try switching STR and EL_pct, so that the default has STR on the right.  And then undo the "default" based on the drawing I gave you last week (sorry).

**Comment by ethansaxenian** [comment]
Question about this: for the 3D view, we want to switch STR and EL_pct, but do we want to do the same for the 2D view?

**Comment by tbyker** [comment]
In any plot with Test Scores, the Test scores should be on the vertical axis.  When plotting STR vs El_pct, I don't have a super strong feeling about which appears on the vertical and which on the horizontal.  But if I have to pick, I would probably put STR on the vertical.



**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Is this something that is absolutely necessary? In my attempts this has made the code very messy and unintuitive.

**Comment by tbyker** [comment]
LOL.  Which part?

I am here at my desk.  Want to stop by?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Nevermind, I found an easier way to do it!
