### ISSUE TITLE
Finalizing the module

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#151]
Binary example:
1) can you tell me which table you were looking at in the Job Corps report to get the means so that I can write a little text?
2) Can you put the information about the estimated line above the sample plot as we do in the continuous example?  (like earnings_hat = beta_0_hat .... in the beta form and also with the estimate for the relevant sample at hand?
3) When switching from continuous to binary, can you make sure the "standardize" button gets unclicked so that someone starts out in the unstandardized mode.  If you were in standardize in continuous and switch to binary the standardize button remains clicked.  

Working on text for the menu page and for the intro

**Comment by ethansaxenian** [comment]
The table is on page 20 and the values are on page 21

**Comment by tbyker** [comment]
Text...(Amanda, what do you think?)

**Menu text**: The sampling distribution of the OLS estimators beta_0_hat and beta_1_hat are approximately normal – this is analogous to what we show for the sample mean with the Central Limit Theorem module.

**Intro Text**: Like the sample mean, the OLS estimated slope and intercept are random variables with sampling distributions.  The Central Limit theorem states that the distribution of the sample average is approximately normal when the sample size is large.  This incredibly useful attribute of the sample average also holds for our OLS estimators beta_0_hat and beta_1_hat!

**Comment by tbyker** [comment]
Can you include a link to the report.  I think have a couple different ones.  thanks!!!

**Comment by ethansaxenian** [comment]
[jobcorpimpactbenefit.pdf](https://github.com/ProfessorAmanda/econsimulations/files/6909212/jobcorpimpactbenefit.pdf)

**Comment by tbyker** [comment]
When writing beta_hats I am hoping you can use the symbol.

**Comment by ProfessorAmanda** [comment]
Intro text looks good! 

I think the menu text can just say something like: "The sampling distributions of the OLS estimators beta_0_hat and beta_1_hat are approximately normal."

**Comment by tbyker** [comment]
Ok.  I agree with Amanda.  You don't need the part with the dash on the menu page

**Comment by tbyker** [comment]
do I need to npm install to see changes.  Or just git pull and then npm start?

**Comment by ethansaxenian** [comment]
```
git pull
npm start
```
should be all you need!

**Comment by tbyker** [comment]
Have you done the changes 2 and 3 above and added the text?  No prob if not, I am just not sure if it is updating if so.

**Comment by ethansaxenian** [comment]
Yep, this should be on the `finalize-ols` branch.

**Comment by tbyker** [comment]
The equation in the binary case should be:

earnings_hat=beta_0_hat + beta_1_hat Job Corps.  Not the study example anymore


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
> The equation in the binary case should be: earnings_hat=beta_0_hat + beta_1_hat Job Corps. Not the study example anymore

Good catch - fixed.

**Comment by tbyker** [comment]
I think this module is looking great and ready to deploy.  As I say, I may add a little text about the Job corps example, but we can deploy now and add that later.  This will also tie in the next module about -- the LLN for regression module.  I will sketch that out this weekend.

right now I have to get my blood drawn because all of you made me paranoid at the baseball game that the rash on my arm could be lyme disease!!!!!!!!!!!!!  And Amanda knows well that having my blood drawn is a huge phobia for me and in fact, I already had a failed attempt at the dr office this morning!  So headed to the lab after having nearly drown myself drinking water.

Another potential thing to work on if you have run out of things for the day is the think about reorganizing the home/menu page.

T


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
Yikes! I hope it isn't lyme!

The reorganization of the menu is already done! There is a pull request for it currently!

**Comment by tbyker** [comment]
Oh, I thought I saw something about that but didn't see it.  Is there a branch for it?  I can look.....procrastinating going to the lab............!!!!!!!!!!!!!


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
The branch is called `menu-changes`

**Comment by tbyker** [comment]
cool.  Can we make the font for the module title stand out a little bit more?  Maybe a little bigger than the rest of the text and bold?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
* module titleS

like "Omitted Variable Bias"  etc and maybe a different color.


OK.  I'm really going to the lab now.



**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
