### ISSUE TITLE
Ready to deploy again

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#158]
Just fixed the sample mean rounding bug

**Comment by tbyker** [comment]
ok.  I am mildly traumatized.  Was stuck with a needle 4 times before they got blood!  Sorry if you are squeamish!  Anyway, I am heading home!  I will sketch out the new module this weekend!

T

**Comment by tbyker** [comment]
Also, sorry, I missed a few steps.  Is everything on master now or should I still be looking at different branches?
