### ISSUE TITLE
Couple of small website items

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#159]
1. There is a typo on the menu page for the definition of Omitted Variable Bias ("on" vs "of", I think).
2. Is the expression for OVB correct? Should it be beta 1 hat converging in probability to something? (It's early and I have no idea). Worth checking, esp. because it's in the paper too.
3. Can we include a link to the teaching materials site on the front page? Link: https://amandagreggeconomics.com/statistics-simulations-project/

**Comment by ethansaxenian** [comment]
How do we want the link to appear?

Also, I have no idea about the OVB expression!

**Comment by tbyker** [comment]
Yeah, the ding dong OVB expression is wrong.  The hat should be on the left-hand side beta (not the right-hand side one)!  Dang it.  Can you please correct it on the site?  I will work on getting it corrected in the paper.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
