### ISSUE TITLE
Error: Failed to Compile

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#16]
I merged the pull request, ran git pull, and tried to run locally. I got the error message: "Failed to compile. Module not found: Can't resolve 'probability-distributions' in '/Users/agregg/Documents/EconomicsSimulations/src/components/OmittedVariableBias' " 

Would be great to fix before we meet today!

**Comment by ethansaxenian** [comment]
probability-distributions is a new package I installed to generate datasets. Try running `npm install` to download the package locally.

**Comment by ProfessorAmanda** [comment]
Thank fixed it! Thank you!
