### ISSUE TITLE
Allow User to add a new point to the Least Squares set of points

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#165]
After they add a new point, they can try to reestimate the line and then also show the new best fit line.

Experiment with making the slider go to zero for number of points.

**Comment by tbyker** [comment]
what is the branch to look at this?  I tried add-points.  Must not be that

**Comment by ethansaxenian** [comment]
The branch is `click-points`. 

The branch is always listed on the corresponding Pull Request! :)

**Comment by tbyker** [comment]
you say that like I am looking at the pull requests! :)

**Comment by tbyker** [comment]
Ok.  I agree this is amazing.  But we need to somehow explain this to users.  One way is to have this feature turned off as a default (is that possible) that the user can turn on after they have used the default setup.  And have some text above the button that explains the point of this amazing feature

**Comment by ethansaxenian** [comment]
Do we not like the text below the plot?

**Comment by tbyker** [comment]
Ah, it was so small I didn't see it!  Sorry!

Is it possible to have it turned off as a default, because we don't want people accidently adding points when they click if they don't mean to.  Can we have a (bigger, more prominently placed) button that says "turn this on to add new points and see what happens to the estimated line" or something like that?


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
