### ISSUE TITLE
Text for Multiple Regression and New dataset

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#166]
Menu Text
Intro Text

Dataset based on the Job Corps example (add gender or age)

**Comment by ethansaxenian** [comment]
Here's a screenshot of the new dataset with two binary variables (ignore the axis labels for now). I don't think it looks very good.

![Screen Shot 2021-08-02 at 5 48 23 PM](https://user-images.githubusercontent.com/67524957/127928233-9bfd8ea0-cf33-4eb5-85ce-089303111276.png)

**Comment by ProfessorAmanda** [comment]
If it's right (and I think it is), though it's not aesthetically pleasing, it's going to be incredibly useful for teaching. Did you try fitting the plane?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tbyker** [comment]
I agree it looks “weird” but not wrong. Can you label the axes with the new variables. And we can play around with what it looks like to fit the plane. I’ll also make a “continuous “ years of schooling variable and we can see what that looks like (be warned it will have a negative intercept)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tbyker** [comment]
I made a new issue.  Sorry. Will attach new dataset to email


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
So here is the fitted plane (again, ignore the axis labels). The problem is that the plane doesn't extend past 0 in the x or y direction. This is because the library we're using uses array indices for the surface, i.e. the first value in the array will always be x = 0, the second x = 1, etc. Hopefully there's a way to change this but I'm not confident.

![Screen Shot 2021-08-03 at 9 35 39 AM](https://user-images.githubusercontent.com/67524957/128024798-b0aff43d-3b32-455b-90ec-c9ead17ff1be.png)

**Comment by ethansaxenian** [comment]
Perhaps it doesn't need to extend past 0. How does this look?

![Screen Shot 2021-08-03 at 9 59 27 AM](https://user-images.githubusercontent.com/67524957/128028542-ef1ae888-89c1-4e96-90d7-1b73a31f0dcd.png)

**Comment by tbyker** [comment]
Simplify text in display options as we discussed and make the best fit toggle a separate button.
Add the estimated line as the graph title

**Comment by tbyker** [comment]
Titles for the different datasets:
1) California Schools Data
2) CPS Earnings Data
3) CPS Log Earnings Data
