### ISSUE TITLE
Possible to have all three graphs on one line?

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#18]
Can we adjust the spacing of the graphs in the Joint Distributions simulation so that all three graphs appear on one line (as before)?

**Comment by DavidGmidd** [comment]
Hello,

 I created a pull request for this, but let's review it to ensure it looks as expected before merging.
________________________________

**Comment by ProfessorAmanda** [comment]
Can we get the graphs closer together and make them larger? Let's discuss what has changed when we meet.
