### ISSUE TITLE
Consolidate / remove old branches

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#180]
Before we end for the summer, it would be a good idea to start to clean up the repository. We now have many disused branches, the content of which is completely merged to master. Can we get rid of as many as possible?

**Comment by ethansaxenian** [comment]
Ah, yes. What (I think) you are seeing is all the branches on your local repository. When we delete a branch from GitHub (which we do after every pull request), that branch stays on your local computer. To delete a branch locally, run `git branch -d [branchname]`. Alternatively, I just did a quick google search and found this command: `git branch --merged | egrep -v "(^\*|master|development)" | xargs git branch -d`, which *should* delete all old local branches ([source](https://devconnected.com/how-to-clean-up-git-branches/)).

**Comment by ProfessorAmanda** [comment]
Boom! That worked great. Thanks for teaching me something new! Let's leave this issue open in case Tanya would like to do the same.

**Comment by ProfessorAmanda** [comment]
Actually I'm going to just move your reply to the github cheat sheet issue.
