### ISSUE TITLE
Simulate Type I Error for F Distribution

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#196]
Hi all, sorry it took me seeing the replication example to realize that what we really should implement is a simulation of Type I error for ANOVA. I think this is how to do it.

- Have a button titled "Simulate Type I Error for ANOVA" to reveal inputs for the user: "Number of Populations" and "Tolerance Alpha[Symbol]" and text "The null hypothesis H_0 is that \mu_1 = mu_2 =.... mu_[number of populations user has entered]"
- Below the text, there should be an input for "Set mean of all populations:"
- Then, a button for "generate populations." They can be displayed horizontally, vertically, or a combination, as we're not going to show the samples (I don't think so, at least)
- Then, the user can set the sample sizes and the number of replications to draw from these populations.
- We will generate and plot the resulting value of F for each of the sets of samples drawn.
- The null hypothesis is rejected for all F statistics that would give a p-value less than the tolerance alpha. (This is simpler than it was for the t-distribution, because we don't have to worry about "sides" or different kinds of alternative hypotheses). I'd love to get an F critical value instead of relying on the p-value method, but I don't see an easy way to do this in jstat, so we can live without it.
- Show a summary of the result: "We rejected the null hypothesis in [Percent]% of replications."

What do you think? Give it a shot?

**Comment by ethansaxenian** [comment]
Why don't we simply use the already generated populations for this simulation?

**Comment by ProfessorAmanda** [comment]
Good question! Type I error is when we reject a true null hypothesis. In the case of this test, the null hypothesis is that the population means are all equal. So, to simulate type i error, we have to impose that restriction, which will be different from the populations we show above. Does that answer your question?

**Comment by ethansaxenian** [comment]
It does!

So we are also sampling from each population a different number of times - is the f-statistic being calculated based on the samples from each individual population? i.e. if 5 populations are generated there will be 5 f-statistics that are plotted.

Also, do we need to plot all the populations? Since they all have the same mean I don't think this will be particularly useful.

**Comment by ProfessorAmanda** [comment]
Great!

Ah, right, this is a little confusing. So, say we generate 5 populations. One replication would designate taking a sample from each population (ie, 5 samples) to get to a single F stat.

I can see your point about the populations being redundant, but let's show them all. They'll gave the same means and standard deviations, but they'll have different individual points, and we want to remind the user about the group structure

And that reminds me: the user needs to choose the population standard deviation, too. We can have them do that when they set the pop mean.

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419<tel:+18024433419>
Pronouns: she/her/hers
________________________________

**Comment by ethansaxenian** [comment]
> Ah, right, this is a little confusing. So, say we generate 5 populations. One replication would designate taking a sample from each population (ie, 5 samples) to get to a single F stat.

Gotcha, I misunderstood the 3rd bullet point - I thought the number of replications for each population would be different.
