### ISSUE TITLE
Text/Edits for Multiple Regression and Consistency 

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#215]
I am uploading the current draft of the document I showed you this morning.  There are still a few things I need to add, but I wanted you to be able to get started.  I will upload a new version later and highlight what is new.

**Comment by tbyker** [comment]
looks like the file didn't upload.  Trying again... had to convert to pdf
[Text_Menu_etc_Summer_21.pdf](https://github.com/ProfessorAmanda/econsimulations/files/7033211/Text_Menu_etc_Summer_21.pdf)

**Comment by ethansaxenian** [comment]
One quick note: for the Large Outliers example, we are not adding a 0 to the entries, we are multiplying them by 2. (multiplying by 10 is too much). How should we change the text to reflect this?

**Comment by tbyker** [comment]
yes, sorry.  I couldn't remember what we were doing.  Adding a zero is a more plausible "typo" , but multiplying by 2 is fine.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by tbyker** [comment]
California Schools data description:

This data is California Standardized Testing and Reporting data for 420 elementary school districts in California for 1999.  This dataset is used throughout Stock and Watson, Introduction to Econometrics and was originally obtained from the California Department of Education (www.cde.ca.gov).
