### ISSUE TITLE
Which intro text to use?

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#22]
The current state of Confidence Intervals has two different introductory paragraphs depending on the distribution type that is chosen.

If Normal: 
"This simulation demonstrates how confidence intervals provide an estimate for the location of the true population mean µ. In this exercise you will first choose 1) whether to assume that you know the true population standard deviation and 2) what confidence level to impose. Then, you will take random samples from the population, calculation a sample mean for each, and construct confidence intervals around those sample means. The proportion of confidence intervals that contain the true mean corresponds to the chosen confidence level!"

If Uniform, Exponential, or Chi-Squared:
"The purpose of this simulation is to show that the formula we develop in class for a “reasonable margin of error” around the sample mean works. About 95 out of 100 intervals we generate using the formula for a 95% confidence interval will contain the true population mean 𝜇. And, what is cooler, this formula will work regardless of the underlying population distribution."

Which one do we want to keep?

**Comment by ProfessorAmanda** [comment]
It should be the first one! Great catch.
