### ISSUE TITLE
Add equations for Omitted Variable Bias

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#280]
Students requested to be able to see the equations of the original and corrected lines in the Omitted Variable Bias module. Possible to add these, maybe on the right? They will need to update any time the equation would change.

**Comment by ProfessorAmanda** [comment]
I merged the pull request! I think we're good to go unless you all have more tweaks you'd like to make.

**Comment by waynew99** [comment]
> I merged the pull request! I think we're good to go unless you all have more tweaks you'd like to make.

Thanks! I think we're good to go!
