### ISSUE TITLE
Create deployment-ready version of master branch

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#29]
Hi folks, would you say that the modules are ready for deployment, except for confidence intervals? If so, it'd be great to have a version of the master branch with confidence intervals removed from the main menu. Then I can get it up on the web. In the last version I saw of the master branch, confidence intervals were included on the main menu.

**Comment by ethansaxenian** [comment]
Actually, confidence intervals should be ready for deployment, although it might be best to go over it as a group first. I will create a new branch called `deployment` that should have the first 5 modules in a deployable state.

**Comment by ProfessorAmanda** [comment]
Thanks! If nothing else, I'm holding up deploying Confidence Intervals, because I need to write some text to go in the main menu.
