### ISSUE TITLE
Examples of Teaching Journal Papers

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#290]
[TeachingQuantitativeMacroToUndergrads_March2022[26].pdf](https://github.com/ProfessorAmanda/econsimulations/files/8909978/TeachingQuantitativeMacroToUndergrads_March2022.26.pdf)
This is a Macro example and one that we will cite in developing the first Macro Module.

Here is a link to the paper Amanda and I wrote about an early version of the app: http://downloads.journalofeconomicsteaching.org/2021/2021-14.pdf

**Comment by ProfessorAmanda** [comment]
Wayne's got it!
