### ISSUE TITLE
Joint Distributions: DOTS

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#34]
Ideas to help with the "blob" problem:
1) smaller dots
2) boarder around dots

Ideas for the the scroll over pointer circles:
1) could we make that circle hollow?
2) If we are going to have a tool tip, can it say "parent" and "child"?

**Comment by ethansaxenian** [comment]
![Screen Shot 2021-06-21 at 1 57 27 PM](https://user-images.githubusercontent.com/67524957/122806728-ae88e080-d298-11eb-968f-bbf6f9b8954e.png)

I was able to figure out how to change the color of the selected node! How does this look?

**Comment by tbyker** [comment]
I like this better!  Can the selected node marker be on top rather than behind the existing points?

**Comment by ethansaxenian** [comment]
There is a way to do this, but it introduces some complications. Basically, in order to handle larger datasets (like ours, with 1,000 data points), the nivo plotting library has a special type of plot suited for these larger datasets, which disables certain features, including the one we'd need here. If we use the normal plot, the sheer number of points makes the animation of the plot really laggy. If we cut the number of points in half to around 500 it becomes much more bearable.

**Comment by ethansaxenian** [comment]
Another option is to vary the colors of the individual dots like so (perhaps only needed for the rightmost chart):

![Screen Shot 2021-06-22 at 1 14 04 PM](https://user-images.githubusercontent.com/67524957/122970318-bf4e5a80-d35b-11eb-9192-a151aae83adf.png)

It could also be a smaller range of color values:

![Screen Shot 2021-06-22 at 1 34 51 PM](https://user-images.githubusercontent.com/67524957/122972893-a1cec000-d35e-11eb-8734-fb9e0e82688c.png)


This may be misleading, however, as students may assume that different colors mean different things, which is definitely _not_ the case  here

**Comment by tbyker** [comment]
hmmm.  I don't love different colors because it implies something is different for some points, which as you point out, is not true.  What would this whole thing look like if we went with the only 500 data points option?  Would that solve many problems at the same time?

**Comment by ethansaxenian** [comment]
This is what it looks like with 500 points

![Screen Shot 2021-06-22 at 1 58 14 PM](https://user-images.githubusercontent.com/67524957/122975980-e740bc80-d361-11eb-802b-49aaf3c1c1f3.png)

**Comment by tbyker** [comment]
And then can we do stuff like a hollow circle over the selected node etc?

**Comment by ethansaxenian** [comment]
This will only allow us to have the selected node pop to the front, like so:

![Screen Shot 2021-06-22 at 2 05 28 PM](https://user-images.githubusercontent.com/67524957/122976925-e8beb480-d362-11eb-88ee-fa89fea6a014.png)

But note we can only do this with the rightmost plot. If we add it for all three it becomes too laggy.

**Comment by tbyker** [comment]
oh, hang out, what does laggy mean?  So the left plots have 1000 points each the right only has 500?

**Comment by ethansaxenian** [comment]
No, they both have only 500 points. But with three plots, it will be checking all 1500 points every time the mouse is moved, which slows down the animation.

The latest screenshot I posted disables the animation for the two left plots, which results in a much smoother webpage.

**Comment by tbyker** [comment]
The dots will still be "live" in the left plots though, right/correct?, in that when you mouse over a point on the right it will still pick the correct corresponding points on the left, correct?

**Comment by ethansaxenian** [comment]
Yes! The only difference is that the selected dots on the left plots won't "pop" to the front.

**Comment by tbyker** [comment]
This seems like a good solution!
