### ISSUE TITLE
Joint Distribution - fix axes

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#35]
Axes should be fixed at 40 to 100

**Comment by ethansaxenian** [comment]
Do we want to fix the y-axes for the parent and child plots as well?

**Comment by ethansaxenian** [comment]
![Screen Shot 2021-06-21 at 1 06 15 PM](https://user-images.githubusercontent.com/67524957/122800898-7b8f1e80-d291-11eb-8c62-102160902101.png)

Here is a screenshot with fixed axes. As we can see some points will extend over the axis ticks. Is this ok? One solution would just be to remove any points that are outside of these bounds.

**Comment by tbyker** [comment]
Hmmm.  I don't love things spilling off the graph.  I would prefer not to remove points (or at least not very many).  Can we reduce the max and min means that user can enter by 5 each (or could increase the axes by 5 each, but I prefer the former so that the scale isn't so small).  If we do that, would the number of points you need to remove at the extremes be pretty small.

**Comment by ethansaxenian** [comment]
With the current mean bounds (60 - 80), there never seems to be more than 10 points that would need to be removed (at most 1% of the total).
