### ISSUE TITLE
OVG

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#41]
<img width="791" alt="ovb" src="https://user-images.githubusercontent.com/66968295/122997830-6346fe80-d37a-11eb-82de-989e983704da.PNG">

Is there a reason why the graph is so looooong?  Does this relate to changes you made to the code?

**Comment by tbyker** [comment]
btw, This comes up because I was going to use a screen shot of that scatter to start my mock up of the new CLT for regression module

**Comment by ethansaxenian** [comment]
Yeah, we probably lost some styling somewhere.

How does this look? The width of the graph is now around 75% of the screen width. However on a large screen (which it looks like yours is), it will still appear fairly wide.

![Screen Shot 2021-06-22 at 5 17 16 PM](https://user-images.githubusercontent.com/67524957/123000536-b2daf980-d37d-11eb-87af-63038a0e5622.png)

**Comment by ethansaxenian** [comment]
One trick would be to adjust the size of your window and take the screen shot from there.

**Comment by tbyker** [comment]
Yes, for the sake of the screen shot, I can figure that out.  But is this something we can fix in general in terms of styling at some point?

**Comment by tbyker** [comment]
Definitely not a rush.  But this is the previous scaling for reference (from our video walk through): 
![image](https://user-images.githubusercontent.com/66968295/123002253-b7a0ad00-d37f-11eb-85fc-d9c58ff8e9ea.png)

**Comment by ethansaxenian** [comment]
Would you prefer it to be a fixed size or relative to the window size?

**Comment by tbyker** [comment]
Good question.  Seems like relative to window size seems preferable, but I'll trust your judgement.  This seems like a general issue for the application overall.  Maybe we can look at/ discuss this next time we meet more broadly.
