### ISSUE TITLE
New Module: "Beta_1_hat is normally distributed (too)!!"

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#42]
[Mockup_New_Regression_Slope_CLT_Module.pdf](https://github.com/ProfessorAmanda/econsimulations/files/6697570/Mockup_New_Regression_Slope_CLT_Module.pdf)

I am attaching a PDF of my first attempt at a mockup of this new module.  The new module is shown side by side with the current CLT module with a similar series of steps.

**Comment by tbyker** [comment]
We could start with the data generating process (DGP) from the OVB module.  But eventually I might pick another example, but that should just be a matter of changing that DGP equation.

**Comment by ethansaxenian** [comment]
![IMG_2569](https://user-images.githubusercontent.com/67524957/124170145-10a1cc80-da75-11eb-997d-8da976bb924d.jpg)

**Comment by ethansaxenian** [comment]
@tbyker, @ProfessorAmanda it would be great if you could provide some values to use for generating the data at some point soon! Also a name for the module!

**Comment by tbyker** [comment]
Can you start with the DGP from OVB using beta=3, delta=2.5, Cov=-9 (ie. Corr=-0.5).  Alternatively, I can send you a dataset (like an actual dataset), but if you can draw a "population" from the OVB module with the above parameters, that would give us more flexibility to tweak things.  Let me know if you are having trouble seeing how the data generation is happening in OVB -- you can stop down or send me some code.

**Comment by tbyker** [comment]
oh.  and let's call the module: "Sample Distribution of OLS estimators"  I know, kind of boring!  Sorry!

**Comment by ethansaxenian** [comment]
It it completely necessary to use the beta/delta formula here? It would be much easier to have a mean and standard deviation for the two variables and generate the data using multivariate normal.

**Comment by tbyker** [comment]
Do you mean you want to use the procedure from joint distributions?  Why is the other hard?  Can't you just pull it from OVB?  I don't have a super strong feeling about this at least for getting things started for an initial population.  If you want to generate an initial scatter the easiest possible way that is fine.

**Comment by ethansaxenian** [comment]
@tbyker @ProfessorAmanda what else can @DavidGmidd and I work on for this module?

**Comment by tbyker** [comment]
Can I check out the current version?  meaning, what do I need to type into the command window.  I am here btw, if that is easier

**Comment by ethansaxenian** [comment]
Navigate to the project (I believe that's `cd desktop/econsimulations` for you)
`git checkout master`
`git pull`
`npm start`

**Comment by tbyker** [comment]
It is looking really good.  I have a few mostly cosmetic things:
1) the population plot is still really long and skinny
2) The first time I tried it, text came up about the sample slope, but now it is not coming up any more (weird?)
3) In the initial phase when user is manually taking samples:
a) can the distribution plot be loaded (like in CLT) so that even these initial sample slopes are being plotted there
b) Can the text for each sample say: Estimated OLS line: Test Score = β₀ + β₁Study Hoursᵢ (with hats on the Test Score and betas _ I'm not getting that to show here in the text editor) and then under that give actual estimate for intercept (β₀) and slope ( β₁).
4) can you automatically clear out the distribution plot when ever the user runs the simulation again?

**Comment by ethansaxenian** [comment]
1. Do you want the plot to be square?
2. What was the text you were seeing? This is what I see: ![Screen Shot 2021-07-06 at 2 31 57 PM](https://user-images.githubusercontent.com/67524957/124649785-ed0cc680-de66-11eb-8ece-6c43ae380ecf.png)
3. a) Yes, definitely - do you want any part of the module to be hidden or should it all be visible initially? (see CLT vs Confidence intervals)
    b) Where should this text be? Also I'm not sure how to type the β with a hat... can you send the character via email?
4. Do you want the "clear" button itself as well? Or would that be redundant now?

**Comment by tbyker** [comment]
Its the population plot that is particularly "skinny" 
![image](https://user-images.githubusercontent.com/66968295/124651802-61486980-de69-11eb-88dd-8419808e872a.png)

**Comment by tbyker** [comment]
And yes, the "slope" text is back.  Maybe I was just missing it earlier.  

When I try to copy in the hat, it isn't working in this text editor:  β ̂_0.  Here is a screen shot:

![image](https://user-images.githubusercontent.com/66968295/124652338-06fbd880-de6a-11eb-987e-06b51b612761.png)

**Comment by ethansaxenian** [comment]
How are you typing this - LaTex?

**Comment by tbyker** [comment]
I guess I would put that where it says "Sample X" currently.

**Comment by tbyker** [comment]
I am actually using the equations editor in MS Word.  But I could get the LaTex code if that is helpful

**Comment by ethansaxenian** [comment]
> I am actually using the equations editor in MS Word. But I could get the LaTex code if that is helpful

No worries, I was just wondering if I could copy and paste the character but that might not actually work.

**Comment by ethansaxenian** [comment]
> And yes, the "slope" text is back. Maybe I was just missing it earlier.
> 
> When I try to copy in the hat, it isn't working in this text editor: β ̂_0. Here is a screen shot:
> 
> ![image](https://user-images.githubusercontent.com/66968295/124652338-06fbd880-de6a-11eb-987e-06b51b612761.png)
> The "hat" implies that it is an estimate

Is there supposed to be a subscript on "Test Score"?

**Comment by tbyker** [comment]
yes, an  "i"  It looks like somehow I lost the "dot" there

**Comment by tbyker** [comment]
I tried the same series of commands and I got a "failed to compile" error.  I can look at it tomorrow, no need to worry about it this evening.  just wanted to let you know

**Comment by ethansaxenian** [comment]
Ah, I installed a new package, so I believe you will need to run `npm install` before `npm start`

**Comment by tbyker** [comment]
Looking quickly while on a Selectboard meeting. Looking good.  I was hoping the that under the equation with the betas to list it with the actual numbers.  So, two lines.  The second would state the estimated intercept and slope.  

for example:

Test Score_hat_i= 70.2+0.2 Study Hours_i

**Comment by ethansaxenian** [comment]
Ah, I see. I will make a separate issue for this

**Comment by tbyker** [comment]
Other ideas to discuss tomorrow:
1) add a standardize button (as in the CLT module)
2) Somehow alert the user that they cannot select a sample size larger than the population size.
3) talk about how hard it is to change the population, for example as an additional module.  Like what if I gave you an actual set of data.  For example, I would like to try to use this real world example as a randomized control : https://www.mathematica-mpr.com/-/media/publications/pdfs/jobcorpimpactbenefit.pdf
