### ISSUE TITLE
Confidence Intervals Table Header

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#46]
![Screen Shot 2021-06-23 at 7 06 15 PM](https://user-images.githubusercontent.com/67524957/123178851-18021e00-d456-11eb-98d1-26d63efe9dd7.png)

In order to make this table scrollable and have the table headers fixed in place while scrolling, I had to add a white background to the top which obstructs the background image, as seen above. I think this looks kind of ugly.

I see two alternative options:
- don't fix the header in place while scrolling.
- remove the fixed table height and let the table extend downwards as far as it needs to.

What do we think? We could also just leave it as is. @DavidGmidd perhaps you know of a solution?

**Comment by tbyker** [comment]
I'm not sure what looks ugly about this.  I am generally pretty picky about design.  Maybe I am just missing it in the screen shot.  Can you show me tomorrow?

**Comment by DavidGmidd** [comment]
Let's discuss it soon. If the background is white because you had to add a div, there are a few things we could try.
