### ISSUE TITLE
Explore Hypothesis Testing simulations online

### ISSUE THREAD

**Issue by DavidGmidd** [ProfessorAmanda/econsimulations#52]

**Comment by tbyker** [comment]
OK!  Don't get too freaked out by this website: https://seeing-theory.brown.edu.  It is a little intimidating.  Beautiful graphics and doing many similar things.  This is an encouragement to keep making ours unique by linking it to economics examples and applications.  They often cite the other websites they use as inspiration so you can click through to those (our CI has a similar flavor to others).  We could do the same citing stuff -- might be a good idea.
