### ISSUE TITLE
Question about Hypothesis Testing data

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#60]
Should the mean for the distribution generated in Hypothesis Testing have a mean of the hypothesized mean (mue_0) or the original population mean? If the latter, what should we set this as? The description in the module says 64 but the module outline (in the word doc) says to bump it up by 5.

**Comment by ethansaxenian** [comment]
Well I just realized that the latter is correct. Still, should this be 64 or 69?

**Comment by ProfessorAmanda** [comment]
Do you mean, the distribution we'll get at the very end? That distribution should have the mean bumped up to 69.

**Comment by ethansaxenian** [comment]
Yes! Should the description in the module itself match this?

**Comment by ProfessorAmanda** [comment]
The description in the module is telling the user what the distribution *used to be*, not what the truth is now (after a treatment has been administered), so it should still say: "To help make an informed guess, note that the distribution of milk production before we changed the feed had a mean of about 64 gallons."

(Also I just noticed a typo: are there two l's in the word "milk?")
