### ISSUE TITLE
Fix twoSample method

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#62]
Currently selecting a twoSample test in Hypothesis Testing has no effect (it still does a oneSample test).

**Comment by DavidGmidd** [comment]
Hello @tbyker @ProfessorAmanda , what values do you want for the two populations? We need mean, sd, and n for each population to calculate the test statistic.

**Comment by DavidGmidd** [comment]
Pop 1: What we have: Mean:64, SD: 3
Pop 2: Mean: Random between 61-66, SD: narrower.

**Comment by ProfessorAmanda** [comment]
I just took a look at the TwoSampleHT branch. I could not enter a sample size or alpha. I'll stay tuned for further updates!

![Screen Shot 2021-06-30 at 5 13 51 PM](https://user-images.githubusercontent.com/53241468/124032414-8bf87500-d9c6-11eb-9b29-813e5d651306.png)

**Comment by DavidGmidd** [comment]
I just fixed it. It seems to work on my computer, please check and confirm.

**Comment by ProfessorAmanda** [comment]
Yes, I can enter a sample size and alpha now!

We can discuss further details tomorrow. I think we'd like to give the user the ability to enter sample sizes for both samples to be taken, and it would be nice to show the mean of sample 1, the mean of sample 2, the std dev of sample 1, the standard dev of sample 2, the difference in means, and then the final test statistic. Also, the test statistic looked too big to be plausible, so double check that you've got the right formula (it might be right, I'm not sure without seeing more of the underlying data).

Keep on truckin!

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________
