### ISSUE TITLE
I had an idea for hypothesis testing: simulate something!

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#63]
It occurred to me this morning that the hypothesis testing simulation should include....a simulation! 

Here is my basic idea. At the very bottom of the page, we could simulate type I error, which is when we reject a null hypothesis that is actually true. We could do this by allowing the user to take many samples from a population that has a mean of the hypothesized mean (mu_0, as they choose) and seeing how often the procedure would lead the user to reject then null. For an alpha of .05, they should reject Ho roughly 5% of the time. 

If we all like the idea, we can go into more specifics.

**Comment by ProfessorAmanda** [comment]
Here are some additional materials outlining how to construct the hypothesis testing simulation for one-sample tests. 
[HypothesisTestingSimulation.pdf](https://github.com/ProfessorAmanda/econsimulations/files/6735800/HypothesisTestingSimulation.pdf)
Panopto video: https://midd.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=db3cb19a-0fa5-4079-8001-ad5601397b1e

One detail I did not mention in the video is: what should be the standard deviation of the distribution that generates the "population" dot plot? It can be the standard deviation of the treated population. Then the standard deviation of the normal curve to the right will be that population standard deviation divided by the square root of the sample size. 

Also note that this version applies to the case where the population standard deviation is known. I'll have to think about what to alter in the case where the population standard deviation is not known.

**Comment by ethansaxenian** [comment]
Thanks for the video, that really helps!

A couple questions:

1. When plotting the sample means, what should the y-values be? 
2. More generally, what is the unit of the y-axis of a bell curve?
3. Why do we have the three cases for rejecting the null hypothesis? Don't we simply need to compare alpha to the p-value and reject/fail to reject accordingly?

**Comment by ProfessorAmanda** [comment]
Good questions! 
1. I think the y-value should be the sample number, similarly to confidence intervals.
2. Ah, right, so we'll be superimposing two graphs with different y-axes. The y-axis for the normal curve is a value called "density," which has no literal meaning (only the area under the curve has meaning). We'll have to play around to get something that scales to make the picture look okay. The y-axis for the sample means will be the sample number.
3. You're right that, with the p-value method, all the steps reduce to a single rule where we compare the alpha value to the p-value.  But "where we are" relative to the distribution actually matters when we want to show what is going on graphically. The p-value calculation does change depending on the alternative hypothesis (is the p-value in the right tail? left tail? multiplied by two?). And in any case, the picture is basically showing the critical value method, since we are pointing out regions where a value of the sample mean would cause us to reject vs. fail to reject. Does that make sense?

**Comment by ethansaxenian** [comment]
3. In terms of what David and I will be coding, do _we_ really care about which tail the mean falls in? Can't we just plot the point, calculate the p-value, and color accordingly?

**Comment by ProfessorAmanda** [comment]
Yes, that's fine! It will give the right answer as long as you calculate the p-value correctly. The user doesn't need to know what is under the hood.

**Comment by ethansaxenian** [comment]
![IMG_2568](https://user-images.githubusercontent.com/67524957/124170025-ebad5980-da74-11eb-9259-1dcac01a436d.jpg)

**Comment by ethansaxenian** [comment]
Just to confirm, the normal curve should be generated with a mean of `mue_0` and a standard deviation of `pop_std_dev / sqrt(sample_size)`

**Comment by ProfessorAmanda** [comment]
Yes, that's right!
