### ISSUE TITLE
Confidence interval plot should indicate the location of the actual pop mean, not 64

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#78]
I was just playing with the confidence intervals simulation, and I noticed an interval I plotted that showed up as green and as containing the pop mean, but on the picture, the line indicating the location of the population mean was not inside the interval. An easy way to fix this, if possible, is to draw the line at the actual location of the mean of the 2000 dots plotted as the population, which will be close to but not exactly 64. 

I'm including a screen shot showing an example of an interval that gave away the inconsistency. In this case, the actual population mean was 64.46, so the interval did contain the true population mean, but it didn't look like it on the picture. (Am I making sense? Sorry!)

![Screen Shot 2021-06-29 at 4 08 34 PM](https://user-images.githubusercontent.com/53241468/123860716-42d7f080-d8f4-11eb-907b-4a956757ca29.png)

**Comment by ethansaxenian** [comment]
Good catch, looks like it was rounding the mean to the nearest whole number, not to the nearest hundredth as intended.
