### ISSUE TITLE
Check "convert" button on Central Limit Theorem

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#80]
![Screen Shot 2021-06-30 at 9 15 03 AM](https://user-images.githubusercontent.com/53241468/123966702-a826f280-d983-11eb-9adf-68415a106f0a.png)

The "convert to std. normal" button on the CLT simulation should rescale each observation of the sample mean using the following formula: (x_bar - popmean) / (popstddeviation / sqrt(sample size)). The picture above shows that the mean has been rescaled correctly, so the numerator is right, but something has gone wrong with the denominator, so the distribution is too narrow. Make sure you are dividing by the standard deviation / sqrt(n) and not the variance / sqrt(n). Would be awesome if we could fix and deploy this by the time I have to present at 11:00 am, but I can present without it if need be!

**Comment by ProfessorAmanda** [comment]
![Screen Shot 2021-06-30 at 9 49 16 AM](https://user-images.githubusercontent.com/53241468/123971926-71071000-d988-11eb-9674-f73bd041746a.png)

Not quite! Now the spread is far too big.

The conversion formula should be:

(Sample mean - Population mean) / Population_std_dev / sqrt(n). 

I suspect that it was dividing by the variance of the sample mean previously. It would be fine to divide by the standard deviation of the sample mean, since std_dev_sample mean = population_std_dev / sqrt(n).

You'll know you have it right when the spread is more like out to values of plus/minus 2 or 3.

**Comment by ProfessorAmanda** [comment]
Shoot, sorry, let me give you some more parentheses:

(Sample mean - Population mean) / (Population_std_dev / sqrt(n)).

**Comment by ethansaxenian** [comment]
I believe it is fixed now

**Comment by ethansaxenian** [comment]
While we're on the topic, should the text on that button change when it is clicked? To emphasize that it can be clicked again to change back?

**Comment by ProfessorAmanda** [comment]
Yes! Looks good. Do me a favor and make me an updated deployment branch, and we'll be good to go. 

Yeah it would be good to change that text, I agree, but that can wait. You can make a separate issue for that and get to it whenever.
