### ISSUE TITLE
Extremely small p-values in Hypothesis Testing?

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#82]
I have been getting some absurdly small p-values while playing around with hypothesis testing. Does this make any sense?

![Screen Shot 2021-06-30 at 1 34 33 PM](https://user-images.githubusercontent.com/67524957/124006163-ea622b00-d9a7-11eb-99f7-293caf740c92.png)

**Comment by ProfessorAmanda** [comment]
With a sample size that huge, yes, it looks right. The test statistic 6.25 tells you how many standard deviations above the population mean that value of the sample mean lies. It's pretty much impossible to get a value 6.25 standard deviations above the mean.

**Comment by ProfessorAmanda** [comment]
We might consider whether we want to "cook the book" with the parameter values to make the outcomes potentially more interesting, for example by making the population standard deviation larger.

**Comment by ethansaxenian** [comment]
> With a sample size that huge, yes, it looks right. The test statistic 6.25 tells you how many standard deviations above the population mean that value of the sample mean lies. It's pretty much impossible to get a value 6.25 standard deviations above the mean.

The sample is only 10% of the population size (2000). Is that considered very large?

**Comment by ProfessorAmanda** [comment]
Hoo yeah. 10% of a population is an enormous number. Especially for test that's this simple. For more complex tests, you need larger samples to avoid type ii error.

**Comment by ProfessorAmanda** [comment]
I should also say, in this case, even a small difference between the hypothesized mean and the sample mean will lead us to reject, since we have set the standard deviation to such a small number. We might consider changing that parameter to make the example more interesting.
