### ISSUE TITLE
OVB Scatter Plot - funky looking

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#85]
Why is the scatter plot so LOOOONG and skinny still?!
![image](https://user-images.githubusercontent.com/66968295/124176983-a4779680-da7d-11eb-80cd-c5c1ff7414a7.png)

**Comment by ethansaxenian** [comment]
@tbyker and I examined this last week and noticed that her zoom was pretty extreme, perhaps leading to this issue. Is this still something we should look at?
