### ISSUE TITLE
jStat.ttest requires degrees of freedom, not sample size

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#86]
For the `jStat.ttest( tscore, n, sides )`, `n` should be the degrees of freedom for the test, not the sample size; that is, `n = sampleSize - 1`.

I figured this out by comparing our results to [this website](https://www.socscistatistics.com/pvalues/tdistribution.aspx)

**Comment by DavidGmidd** [comment]
Good catch! Thanks!
