### ISSUE TITLE
Smaller comments on hypothesis testing + hypothesis testing simulation

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#87]
This is really shaping up! Now that the basic scaffolding is in place, I have some smaller comments to improve exposition.

1. In the one sample test, the default number in the box after "Option 1: These cows.." should probably be 64. 
3. On the graph shown after "reveal," it would be cool to show the location of the hypothesized mean and the location of the true mean with vertical lines labeled as "True population mean" and "mu_0." Maybe mu_0 could be a red line and the true population mean a green line. 
4. In the simulation, similarly to the confidence intervals simulation, can we include a concluding statement about the proportion of samples for which we reject the null hypothesis? "Out of [number] samples, we rejected the null hypothesis [number] times ([percent]%)."

Thanks!!

**Comment by ethansaxenian** [comment]
1, 3, and 4 have now been implemented. I am going to move the others into separate issues as we may have to keep track of them separately.

**Comment by ProfessorAmanda** [comment]
Awesome, and good idea!

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________

**Comment by ProfessorAmanda** [comment]
Small note: In the text "Out of [number] samples, we rejected the null hypothesis [number] times ([percent]%)," I think the percent reported needs to be multiplied by 100. (I saw that we rejected the null .01% of the time, for example, where it probably should say 1%.)

**Comment by ethansaxenian** [comment]
Oops, good catch!
