### ISSUE TITLE
Randomly select the population mean in Hypothesis Testing

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#88]
I believe @DavidGmidd  was working on this

**Comment by DavidGmidd** [comment]
My understanding was that only for the second sample in the scenario of two samples this would happen. Are we having the population in one sample also be produced randomly?

**Comment by ethansaxenian** [comment]
I believe both should be random. @ProfessorAmanda @tbyker can one of you confirm this?

**Comment by ProfessorAmanda** [comment]
Yes, both should have random means. I think this got lost in the shuffle amidst a big list of other things, so I wanted to mention it now.
