### ISSUE TITLE
T Curve

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#90]
Small thing: in the case where the pop std deviation is not known, and you use t, is the graph on the right plotting a normal curve or a t curve? It should be a t curve.

**Comment by ethansaxenian** [comment]
@ProfessorAmanda the curve that is plotted currently is simply a normal curve. Unfortunately I am not sure if it is possible to plot a t curve

**Comment by ethansaxenian** [comment]
Although, if there is a function that generates a t-curve, we could potentially use this instead of generating a population and having highcharts create a curve from that (which is what is happening now).

**Comment by ProfessorAmanda** [comment]
Hi Ethan, so are you saying that the normal curves are generated empirically, i.e. from the data?

**Comment by ProfessorAmanda** [comment]
Ah, gotcha. I think for now a simple solution that keep things kosher would be to just not show the outline of the normal distribution when we use the t distribution.

**Comment by ethansaxenian** [comment]
That is doable.

Out of curiosity, is there a function that will generate a t curve?

**Comment by ProfessorAmanda** [comment]
There is, but it's [ugly AF](https://en.wikipedia.org/wiki/Student%27s_t-distribution#Probability_density_function). 

The normal prob. density, by contrast, is a much simpler beast. 
<img width="206" alt="Screen Shot 2021-07-02 at 11 40 01 AM" src="https://user-images.githubusercontent.com/53241468/124298488-49e84400-db2a-11eb-87f9-8c993ae18234.png">
