### ISSUE TITLE
Small cosmetic changes to two-sample HT

### ISSUE THREAD

**Issue by ProfessorAmanda** [ProfessorAmanda/econsimulations#97]
I have a couple small comments on the user inputs for the two-sample HT module. This is not a first priority, but it should be quick to change when you guys have a moment.

1. Make the inputs, etc the same size as what we have for the first sample size (for symmetry).
2. Change "Sample Size" to "Sample Size for Sample 1" and "Sample 2 Size" to "Sample Size for Sample 2." My change is wordy, but I can't think of a less awkward way to phrase it! 

<img width="788" alt="Screen Shot 2021-07-05 at 12 25 43 PM" src="https://user-images.githubusercontent.com/53241468/124499794-9f239000-dd8c-11eb-8332-ae1108c62b92.png">

**Comment by ethansaxenian** [comment]
How about "First Sample Size" and "Second Sample Size"?
